### PR TITLE
Change request method to "GET" on reroute command

### PR DESCRIPTION
**Pull request by ssassi**
This is useful to avoid errors when mocking requests different than "GET"

### CODE REVIEW

**Comment by seriema** [comment]
Thanks! I just took a quick look at the build failure. Would you mind updating the unit tests? :D

**Comment by seriema** [comment]
I've merged, then changed the unit tests. Thanks for your contribution @ssassi !

**Comment by ssassi** [comment]
No problem!
I was about to modify them, thanks for doing that! The library is being
very useful for me and my team.

**Comment by seriema** [comment]
Super glad to hear it! Would you mind telling me more about how you use it? Anything you'd like to have added? I'm really curious on how it's used in the wild. =) My email is seriema at gmail dot com.

**Pull request merged**
