### PR TITLE
Added query param support

### PR DESCRIPTION
**Pull request by trevcor**
I added support for query params.  Filenames and module names  will replace '?' with '_'.

### CODE REVIEW

**Comment by seriema** [comment]
Wow almost a month has passed already. Sorry @trevcor I've been meaning to take a deeper look at it as I need to consider the implications of how the library is used.

My spontaneous thoughts until next week when my vacation starts and I can think more about it are:
* Should this be the default behavior, or only activated by a `config` flag?
* How does this impact ease of prototyping and debugging, as it requires more static files to be available.
 * Does it matter for us if we type something random in a typeahead type box and not get any response unless we type specific existing words?
* Should we release a new version of the library for every feature?
 * If so, we should probably update documentations, demos, and upload to NuGet at the same time.
* Minor thing, but diffs should be minimal. Whitespace changes should be removed.

**Comment by seriema** [comment]
This fork seems interesting. It uses a config flag. What do you think? https://github.com/jeffsaracco/angular-apimock/commit/e11902362cf55671ee92e4466ce143b36d2972ff

**Comment by trevcor** [comment]
* Probably a config flag would be best.  I needed this feature because my backend is query param heavy but that may not be the case for most people.
* I am using your plugin in conjunction with karma-ng-json2js-preprocessor so that I can use the same json files in my unit tests mocks.  That module combined with your plugin has given me a nice little framework to handle (1) being able to get UI work done ahead of the my api team and (2) standardize how I'm handling mock data in my unit tests.
* I've run into the autocomplete issue and for now I've been dealing with having to type in the exact characters I've created files for.  Maybe we could come up with some type of wildcard scheme?
* I agree about uploading demos and documentation.  I'm not sure the best way to handle the versioning.  If we add this as a config it shouldn't be a breaking change so just this feature alone may not be worthy of a version bump.  
* sorry about the diffs.  I should  re-fork and just make my few changes then pr again.  I also didn't mean to bump the version numbers but I was just making sure I could run all the grunt tasks while testing.  I'm assuming the task that bumps the versions and builds the NuGet package should run on the CI server?

**Comment by seriema** [comment]
I'm extremely happy to hear you're getting use of it!

* Config flag, yeah I think that would be best so we don't break things for others. Breaking changes should require a major version bump as well.
* Do you have some sample of how you're doing this? It seems like a perfect combo! I'd like to add something like that to the docs/demo.
* For typeahead it seems like a perfect example of when you want to use the object config for `$http` instead of the global setting in the browser. Maybe I haven't documented it properly but this combined with the config flag would be a great fit. Also check #16 there might be some way to make it work in conjunction with this.
* I should update the demo on the website. There's just too much text...
* Yeah I'd wait with the bump, and a patch-bump would probably be too small for new features but they should be turned off by default unless they don't affect current users.
* It would be great if you could make a thinner PR. Also check https://github.com/jeffsaracco/angular-apimock/commit/e11902362cf55671ee92e4466ce143b36d2972ff to see a flag-using version.

**Comment by seriema** [comment]
I've added a [contribution guidelines doc](tree/master/CONTRIBUTING.md) as per #22 . I'd love some feedback on it if you have time @trevcor . =)

Otherwise, where are we on this PR? I'd like to try again based on the guidelines I wrote above.

**Comment by trevcor** [comment]
I'll try to get a commit using these new guidelines in the next few days.

**Comment by seriema** [comment]
Awesome! The first thing you might notice is the PR guidelines mentioning use cases and sample usage. I thought we could practice that so I went ahead and created issue #23. Let's continue the discussion there!

**Pull request closed without merging**
