### PR TITLE
Add main entry to package.json for Browserify

### PR DESCRIPTION
**Pull request by ramabouda**
This allow the module to be required with browserify

### CODE REVIEW

**Comment by seriema** [comment]
Good idea! Thank you @raphael-boucher !

I'm not sure why the tests fail on Travis. If you run `npm test` locally, do you get any issues? Because I don't.

Could you `git commit --amend` the first line in your git commit message to something like `feat(apimock): add support for Browserify`? It helps generate my release logs correctly. More info: https://github.com/seriema/angular-apimock/blob/master/CONTRIBUTING.md

**Comment by seriema** [comment]
I hadn't noticed that Angular 1.5 was released recently:
https://github.com/angular/angular.js/releases/tag/v1.5.0

My tests fail with it but not with older versions, so I'm looking into it.

**Comment by raphael-boucher** [comment]
Done!

**Comment by seriema** [comment]
Thanks @raphael-boucher ! Much appreciated!

If you have a test usage scenario for this I'd gladly use it to check that everything's working. I'll try to automate it, or if you have any tips or PR for how to do that it'd be great! I accidentally broke our npm distribution once (see #60) so I'm super careful now. :D

**Comment by raphael-boucher** [comment]
To test this, you need a dummy project with the local angular-apimock in the `package.json` (see https://docs.npmjs.com/files/package.json#local-paths). Then check `npm install` happens without errors.
You can go further and use webpack or browserify to ensure the package can effectively be required, but that sounds like a lot of work...

**Pull request merged**
